### ISSUE TITLE
Retweeted not being saved into the db properly

### ISSUE THREAD

**Issue by ghost** [alexfrancisross/TwitterStream#2]
All tweets appear as "f" in the Retweeted column.

**Comment by mikelewek** [comment]
I'm going to close this. It appears I'm having my own confusion as to what is a retweet and quoted status. Thank you.

**Comment by ghost** [comment]
Favorite and favorite count is not tracking correctly. I will have to confirm retweet and retweet status, but I suspect those are also not working. A guess at this point is that these are issues  coming in from Tweeply.
